import Foundation

/// The 注音 (ㄅ半) character table: a reading (ㄋㄧˇ) to the characters that share it, in the
/// source table's own order — which is the candidate order 注音 shows before any user learning,
/// the same arrangement 三代倉頡 has for 倉頡.
///
/// Line format "<reading>\t<char>", one mapping per line, matching Resources/zhuyin-yahoo.txt
/// (generated by tools/build-zhuyin-table.py from the ㄅ半 table in the open-sourced Yahoo!
/// KeyKey release — see Resources/ZHUYIN-DATA-LICENSE.txt).
public struct ZhuyinTable {
    private var table: [String: [String]] = [:]
    // Per-reading membership sets, used only while parsing for O(1) dedup rather than an O(n)
    // `contains` scan per row — the same shape SimplexTable uses.
    private var seen: [String: Set<String>] = [:]

    public init(text: String) {
        table.reserveCapacity(1_600)
        seen.reserveCapacity(1_600)
        for rawLine in text.split(separator: "\n", omittingEmptySubsequences: true) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix("#") { continue }
            let parts = line.split(separator: "\t")
            guard parts.count >= 2 else { continue }
            let reading = String(parts[0])
            let char = String(parts[1])
            // Same rendering policy as the 倉頡 tables: the bundled table is a faithful conversion
            // of a CNS 11643 "large character set" source, so roughly two rows in three name a
            // supplementary-plane or private-use character that would show as tofu in the
            // candidate window and paste as a box. They are dropped here, in the one place that
            // decides what is renderable, rather than by a second filter in the generator.
            guard !reading.isEmpty, let ch = char.first, char.count == 1,
                  CangjieTable.isRenderableCJK(ch) else { continue }
            if seen[reading, default: []].insert(char).inserted {
                table[reading, default: []].append(char)
            }
        }
        seen = [:]   // parse-time only; not part of the loaded table
    }

    public init(contentsOf url: URL) throws {
        try self.init(text: String(contentsOf: url, encoding: .utf8))
    }

    /// The characters for a reading, in table order. Empty when the reading is unknown — an
    /// unpronounceable combination, or one no character has.
    public func characters(forReading reading: String) -> [String] { table[reading] ?? [] }
    public func hasReading(_ reading: String) -> Bool { table[reading] != nil }
    /// How many distinct readings the table holds (the bundled table has ~1,400).
    public var readingCount: Int { table.count }
}
