#!/usr/bin/env python3
"""Generate Resources/zhuyin-yahoo.txt (zhuyin<TAB>character, one mapping per line).

Source: the ㄅ半 table shipped in the open-sourced Yahoo! KeyKey release,
`YahooKeyKey-Source-1.1.2528/DataTables/bpmf-ext.cin` (the same release, and the same
"large character set" lineage, as the 三代 tables already bundled as
Resources/cangjie-yahoo.txt and Resources/simplex-yahoo.txt). See
Resources/ZHUYIN-DATA-LICENSE.txt for provenance and licensing.

What this converts. A `.cin` chardef row is keyed by the KEY SEQUENCE a 大千 typist
presses ("su3"), not by the reading it spells. Keying the bundled table by the key
sequence would hard-wire 大千 into the data, so every row is translated through the
table's own %keyname map into the zhuyin READING it stands for ("ㄋㄧˇ"), leaving the
keyboard layout a pure key→symbol mapping the app can vary (ZhuyinKeyboardLayout).

Tone convention, matching both the .cin and McBopomofo's data.txt: the first tone is
unmarked and every other tone is a SUFFIX — ㄋㄧˇ, ㄉㄜ˙, ㄦ (first tone).

Line order is preserved exactly: within one reading it is the original table's candidate
order, which is what 注音 shows before any user learning (as 三代倉頡 does for 倉頡).

Usage:
    python3 tools/build-zhuyin-table.py path/to/bpmf-ext.cin
"""
import sys
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Resources", "zhuyin-yahoo.txt")

INITIALS = set("ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙ")
MEDIALS = set("ㄧㄨㄩ")
FINALS = set("ㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦ")
# ˉ (first tone) is never written: the .cin spells it as the absence of a tone key.
TONES = set("ˊˇˋ˙")


def read_cin(path):
    """Return (keyname map, [(key sequence, value)]) from a .cin file."""
    keyname = {}
    rows = []
    section = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("#") or not line.strip():
                continue
            if line.startswith("%keyname"):
                section = "keyname" if "begin" in line else None
                continue
            if line.startswith("%chardef"):
                section = "chardef" if "begin" in line else None
                continue
            if line.startswith("%"):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            if section == "keyname":
                keyname[parts[0]] = parts[1]
            elif section == "chardef":
                rows.append((parts[0], parts[1]))
    return keyname, rows


def reading(keys, keyname):
    """The zhuyin reading a key sequence spells, or None when it is not one syllable.

    Enforces the shape a 注音 syllable has — at most one initial, one medial, one final
    and one tone, in that order — so a row this cannot account for is reported rather
    than silently reordered into something typable.
    """
    slots = ["", "", "", ""]   # initial, medial, final, tone
    last = -1
    for key in keys:
        symbol = keyname.get(key)
        if symbol is None:
            return None
        if symbol in INITIALS:
            slot = 0
        elif symbol in MEDIALS:
            slot = 1
        elif symbol in FINALS:
            slot = 2
        elif symbol in TONES:
            slot = 3
        else:
            return None
        if slots[slot] or slot <= last:   # repeated slot, or out of typing order
            return None
        slots[slot] = symbol
        last = slot
    if not (slots[0] or slots[1] or slots[2]):
        return None      # a bare tone key spells no syllable
    return "".join(slots)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    keyname, rows = read_cin(sys.argv[1])
    if not keyname or not rows:
        sys.exit("ERROR: %s has no %%keyname or no %%chardef rows" % sys.argv[1])

    out_rows = []
    seen = set()
    skipped_key = []
    skipped_value = []
    duplicates = 0
    for keys, value in rows:
        if len(value) != 1:
            skipped_value.append((keys, value))
            continue
        z = reading(keys, keyname)
        if z is None:
            skipped_key.append((keys, value))
            continue
        if (z, value) in seen:
            duplicates += 1
            continue
        seen.add((z, value))
        out_rows.append((z, value))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# zhuyin<TAB>character, in the source table's own candidate order.\n")
        f.write("# Generated by tools/build-zhuyin-table.py from the Yahoo! KeyKey\n")
        f.write("# DataTables/bpmf-ext.cin; see Resources/ZHUYIN-DATA-LICENSE.txt.\n")
        for z, value in out_rows:
            f.write("%s\t%s\n" % (z, value))

    readings = len({z for z, _ in out_rows})
    print("Wrote %s (%d rows, %d readings)" % (OUT, len(out_rows), readings))
    print("  %d duplicate rows dropped, %d rows with a multi-character value skipped"
          % (duplicates, len(skipped_value)))
    if skipped_key:
        print("  %d rows whose key does not spell one syllable skipped: %s"
              % (len(skipped_key), " ".join(k for k, _ in skipped_key[:20])))


if __name__ == "__main__":
    main()
